apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tf4f5z8ai-nodejs 
  janus-idp.io/tekton: tf4f5z8ai-nodejs
  backstage.io/kubernetes-id: tf4f5z8ai-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tf4f5z8ai-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml