apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tf4f5z8ai-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tf4f5z8ai-nodejs 
  name: tf4f5z8ai-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tf4f5z8ai-nodejs 
